Lesson 03
ggsurkov/teachmeskill_cs pull request #1
Opened 2023-08-20 11:50 UTC by ggsurkov

2023-08-22 14:29 UTC, gorodkoartem requested changes

2023-08-22 14:29 UTC, gorodkoartem commented on Root/ErrorExeptionsLib/Class1.cs
> +        public static bool isCorrectIntMonthValue(dynamic value)
все методы должны начинаться с большой буквы

2023-08-22 14:29 UTC, gorodkoartem commented on Root/ErrorExeptionsLib/Class1.cs
> +        public static bool isCorrectIntMonthValue(dynamic value)
dynamic лучше использовать ТОЛЬКО когда того требует ситуация. C# строго типизированный, поэтому типы нужно указывать явно (в данном случае int).

2023-08-22 14:29 UTC, gorodkoartem commented on Root/Task1/Program.cs
> +using System.Xml.Serialization;
неиспользуемые using нужно удалять для чистоты кода

2023-08-22 14:29 UTC, gorodkoartem commented on Root/Task1/Program.cs
> +                switch (inputNumber)
задание чутка не так понял, нужны были сезоны, а не месяцы

2023-08-22 14:29 UTC, gorodkoartem commented on Root/Task4/Program.cs
> +            if (inputNumber <= -5 && inputNumber > -20)
inputNumber <= -5 условие излишнее
оно всегда в этом месте true, тк обратные кейсы отбросились return'ом в первом условии

2023-08-22 14:29 UTC, gorodkoartem commented on Root/Task4/Program.cs
> +            if (inputNumber <= -20)
а здесь вообще if не нужен

2023-08-22 14:29 UTC, gorodkoartem commented on Root/Task4/Program.cs
> +            dynamic insertedValue = Console.ReadLine();
dynamic используется когда тип неизвестен (а это очень редко). Console.ReadLine() возвращает string, так что использовать dynamic здесь неправильно

2023-08-23 21:10 UTC, ggsurkov commented on Root/Task4/Program.cs
> +            dynamic insertedValue = Console.ReadLine();
thx, fixed

2023-08-23 21:10 UTC, ggsurkov commented on Root/Task4/Program.cs
> +            if (inputNumber <= -20)
thx, fixed

2023-08-23 21:10 UTC, ggsurkov commented on Root/Task4/Program.cs
> +            if (inputNumber <= -5 && inputNumber > -20)
thx, fixed

2023-08-23 21:11 UTC, ggsurkov commented on Root/Task1/Program.cs
> +                switch (inputNumber)
oh, my mistake, thank you. I fixed that

2023-08-23 21:12 UTC, ggsurkov commented on Root/Task1/Program.cs
> +using System.Xml.Serialization;
fixed

2023-08-23 21:12 UTC, ggsurkov commented on Root/ErrorExeptionsLib/Class1.cs
> +        public static bool isCorrectIntMonthValue(dynamic value)
ok, fixed

2023-08-23 21:13 UTC, ggsurkov commented on Root/ErrorExeptionsLib/Class1.cs
> +        public static bool isCorrectIntMonthValue(dynamic value)
fixed

2023-09-12 14:53 UTC, gorodkoartem approved these changes

2023-09-16 19:17 UTC, merged